## Sentence similarity

In [ ]:
#   !pip install sentence-transformers

In [1]:
from sentence_transformers import SentenceTransformer

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [8]:
model1 = SentenceTransformer("all-MiniLM-L6-v2")

model2 = SentenceTransformer("all-mpnet-base-v2")

# 

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [17]:
sentences1 = ['it is snowing on this saturday morning',
'it is sunny and cold today',
              'My name is Prashant and I am a data scientist']

embeddings1 = model2.encode(sentences1, convert_to_tensor=True)

print(embeddings1)

sentences2 = ['it was sunny and cold yesterday',
              'Transformers are magical',
              'The new movie is so great']

embeddings2 = model2.encode(sentences2, 
                           convert_to_tensor=True)

print(embeddings2)

tensor([[-0.0027, -0.0058,  0.0022,  ...,  0.0034,  0.0132,  0.0084],
        [-0.0063, -0.0400, -0.0070,  ...,  0.0010,  0.0054,  0.0257],
        [ 0.0355,  0.0440, -0.0445,  ...,  0.0197,  0.0267, -0.0517]])
tensor([[-0.0030, -0.0261, -0.0106,  ..., -0.0084, -0.0118,  0.0041],
        [ 0.0093,  0.0046,  0.0094,  ...,  0.0120, -0.0047, -0.0168],
        [-0.0380,  0.0457,  0.0119,  ...,  0.0508, -0.0084, -0.0068]])


In [18]:
embeddings1.shape

torch.Size([3, 768])

In [19]:
from sentence_transformers import util
cosine_scores = util.cos_sim(embeddings1,embeddings2)
print(cosine_scores)

for i in range(len(sentences1)):
    print("{}  +  {} --- Score: {:.4f}".format(sentences1[i],
                                                 sentences2[i],
                                                 cosine_scores[i][i]))

tensor([[0.5516, 0.0326, 0.0165],
        [0.8136, 0.0527, 0.0584],
        [0.0973, 0.0552, 0.0237]])
it is snowing on this saturday morning  +  it was sunny and cold yesterday --- Score: 0.5516
it is sunny and cold today  +  Transformers are magical --- Score: 0.0527
My name is Prashant and I am a data scientist  +  The new movie is so great --- Score: 0.0237
